<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
    <RootNamespace>binarycache_test</RootNamespace>
    <AssemblyName>binarycache-test</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <OutputPath>$(SolutionDir)bin\$(Configuration)$(Platform)\tests\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NDesk.Options" Version="0.2.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Dependencies.Interop\Dependencies.Interop.csproj" />
    <ProjectReference Include="..\..\DependenciesLib\DependenciesLib.csproj" />
  </ItemGroup>
</Project>