<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <SupportedOSPlatformVersion>6.1</SupportedOSPlatformVersion>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
    <RootNamespace>Dependencies</RootNamespace>
    <AssemblyName>DependenciesGui</AssemblyName>
    <StartupObject>Dependencies.App</StartupObject>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <OutputPath>$(SolutionDir)bin\$(Configuration)$(Platform)\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Mono.Cecil" Version="0.11.4" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Dependencies.Interop\Dependencies.Interop.csproj" />
    <ProjectReference Include="..\DependenciesLib\DependenciesLib.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Images\**\*.png" />
    <Resource Include="Dependencies.ico" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="DragablzCustomHeader.cs" />
    <Page Remove="DragablzCustomHeader.xaml" />
  </ItemGroup>
</Project>