<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
    <AssemblyName>Dependencies.Interop</AssemblyName>
    <RootNamespace>Dependencies.ClrPh</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <OutputPath>$(SolutionDir)bin\$(Configuration)$(Platform)\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Dependencies.Native\Dependencies.Native.vcxproj" ReferenceOutputAssembly="false" />
  </ItemGroup>

</Project>